---
title: "NSCLC - Reference curves for ST2"
author: "Hugo Pedder"
date: "2024-01-29"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  options(knitr.kable.NA = '\\-'),
  fig.height=5, 
  fig.width=7
  )

library(flexsurv)
library(survminer)
library(mfp)
library(rstpm2)
library(ggplot2)
library(tidyverse)
library(BristolTAG)
source("R Functions/NSCLC_functions.R")

# Choose save location
wb <- openxlsx::createWorkbook(title="ST2_ReferenceCurves")

info.df <- data.frame("Title"=c("Fractional polynomial multivariate normal distribution of MCMC samples - means and covariances for reference model parameters",
                                      "Parameters named by the treatment refer to the relative treatment effect for each fractional polynomial coefficient (1-3)"
                                ))

openxlsx::addWorksheet(wb=wb, sheetName="Info")
openxlsx::writeDataTable(wb=wb, sheet="Info", 
                         x=info.df)
```


## Non-squamous patients

This uses the Docetaxel arm of LUME-lung 1

```{r}
# Import data
ipd <- read.csv("ST2 IPD extraction.csv")
```


```{r}
refstudy <- "LUME-Lung 1"

ipd.ref <- subset(ipd, study==refstudy & treatment=="Docetaxel" &
                    outcome=="PFS" & histology=="Non-Squamous")


#### Run models ####
#Exponenetial
mod.exp <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='exponential')
modfit <- data.frame(Model="Exponential", AIC=glance(mod.exp)$AIC, BIC=glance(mod.exp)$BIC)

# Weibull
mod.weib <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='WeibullPH')
modfit <- modfit %>%
  add_row(Model="Weibull", AIC=glance(mod.weib)$AIC, BIC=glance(mod.weib)$BIC)

# Gamma
mod.gengamma <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gengamma')
modfit <- modfit %>%
  add_row(Model="Generalised Gamma", AIC=glance(mod.gengamma)$AIC, BIC=glance(mod.gengamma)$BIC)

# Log-normal
mod.lnorm <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='lnorm')
modfit <- modfit %>%
  add_row(Model="Log-Normal", AIC=glance(mod.lnorm)$AIC, BIC=glance(mod.lnorm)$BIC)

# Log logistic
mod.loglogistic <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='llogis')
modfit <- modfit %>%
  add_row(Model="Log Logistic", AIC=glance(mod.loglogistic)$AIC, BIC=glance(mod.loglogistic)$BIC)

# Gompertz
mod.gom <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gompertz')
modfit <- modfit %>%
  add_row(Model="Gompertz", AIC=glance(mod.gom)$AIC, BIC=glance(mod.gom)$BIC)

# RCS (2 knots)
mod.rcs <- stpm2(Surv(time, event)~1, data=ipd.ref, df=2)
modfit <- modfit %>%
  add_row(Model="RCS", AIC=AIC(mod.rcs), BIC=BIC(mod.rcs))

# Fractional polynomial (2nd order -3, -3)
modseq1 <- readRDS(file="JAGS_Results/ST2_PFS_fpoly1_LUMELung1.NS.RDS")
modseq2 <- readRDS(file="JAGS_Results/ST2_PFS_fpoly2_LUMELung1.NS.RDS")
modseq.fp <- append(modseq1, modseq2)
class(modseq.fp) <- "sequence.fpoly"

modfit.fp <- summary(modseq.fp)
modfit.fp <- arrange(modfit.fp, DIC)

fp.mod <- modseq.fp[["FP_-3_-3"]]

# For FP
surv.fp <- survcalc(fp.mod, 
                    times=seq(1, max(ipd$time[ipd$study==refstudy]), length.out = 100),
                    refstudy=refstudy)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial", AIC=NA, BIC=NA)
```

```{r}
# Standard distributions
modlist <- list("Exponential"=mod.exp, "Weibull"=mod.weib, 
                "Generalised Gamma"=mod.gengamma, "Log-normal"=mod.lnorm,
                "Log Logistic"=mod.loglogistic, "Gompertz"=mod.gom)

surv.df <- data.frame()
for (i in seq_along(modlist)) {
  mod.df <- summary(modlist[[i]], tidy=TRUE)
  surv.df <- rbind(surv.df,
                   mod.df %>% rename(surv=est, upper=ucl, lower=lcl) %>%
                     select(time, surv, upper, lower) %>%
                     mutate(Model=names(modlist)[i]))
}

# Add RCS
pred_surv <- predict(mod.rcs, 
                     type="surv", grid=TRUE, full=TRUE, se.fit=TRUE)
surv.df <- rbind(surv.df,
                 pred_surv %>% rename(surv=Estimate) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="RCS")
                   )

# Add fractional polynomial
surv.df <- rbind(surv.df,
                 subset(surv.fp$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order")
                   )

surv.df$Model <- factor(surv.df$Model)

# Plot all results with KM data
kmdat <- survfit(Surv(time, event) ~ 1, data=ipd.ref,type="kaplan-meier",)
kmdat <- data.frame(time=kmdat$time,surv=kmdat$surv, Model="Kaplan-Meier")

cols <- RColorBrewer::brewer.pal(n_distinct(surv.df$Model)+1, "Set1")

ggplot(surv.df, aes(x=time, y=surv, color=Model)) +
  geom_line() +
  geom_step(data=kmdat, aes(time, surv), color="black") +
  xlab("Time (months)") +
  ylab("PFS") +
  scale_color_manual(values=cols) +
  theme_bw()
```

```{r}
knitr::kable(modfit, col.names=c("Distribution", "AIC", "BIC"),
                  digits=1)
```

```{r}
# Generate covariance matrices (fp.mod)
mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "NS", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                         rowNames = TRUE, colNames = TRUE)
```


## Squamous patients

This uses the Docetaxel arm of LUME-lung 1

```{r}
# Import data
ipd <- read.csv("ST2 IPD extraction.csv")
```


```{r}
refstudy <- "LUME-Lung 1"

ipd.ref <- subset(ipd, study==refstudy & treatment=="Docetaxel" &
                    outcome=="PFS" & histology=="Squamous")


#### Run models ####
#Exponenetial
mod.exp <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='exponential')
modfit <- data.frame(Model="Exponential", AIC=glance(mod.exp)$AIC, BIC=glance(mod.exp)$BIC)

# Weibull
mod.weib <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='WeibullPH')
modfit <- modfit %>%
  add_row(Model="Weibull", AIC=glance(mod.weib)$AIC, BIC=glance(mod.weib)$BIC)

# Gamma
mod.gengamma <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gengamma')
modfit <- modfit %>%
  add_row(Model="Generalised Gamma", AIC=glance(mod.gengamma)$AIC, BIC=glance(mod.gengamma)$BIC)

# Log-normal
mod.lnorm <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='lnorm')
modfit <- modfit %>%
  add_row(Model="Log-Normal", AIC=glance(mod.lnorm)$AIC, BIC=glance(mod.lnorm)$BIC)

# Log logistic
mod.loglogistic <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='llogis')
modfit <- modfit %>%
  add_row(Model="Log Logistic", AIC=glance(mod.loglogistic)$AIC, BIC=glance(mod.loglogistic)$BIC)

# Gompertz
mod.gom <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gompertz')
modfit <- modfit %>%
  add_row(Model="Gompertz", AIC=glance(mod.gom)$AIC, BIC=glance(mod.gom)$BIC)

# RCS (2 knots)
mod.rcs <- stpm2(Surv(time, event)~1, data=ipd.ref, df=2)
modfit <- modfit %>%
  add_row(Model="RCS", AIC=AIC(mod.rcs), BIC=BIC(mod.rcs))

# Fractional polynomial
modseq1 <- readRDS(file="JAGS_Results/ST2_PFS_fpoly1_LUMELung1.S.RDS")
modseq2 <- readRDS(file="JAGS_Results/ST2_PFS_fpoly2_LUMELung1.S.RDS")
modseq.fp <- append(modseq1, modseq2)
class(modseq.fp) <- "sequence.fpoly"

modfit.fp <- summary(modseq.fp)

fp.mod <- modseq.fp[["FP_-3_-3"]]

# For FP -1 0
surv.fp <- survcalc(fp.mod, 
                    times=seq(1, max(ipd$time[ipd$study==refstudy]), length.out = 100),
                    refstudy=refstudy)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial", AIC=NA, BIC=NA)
```

```{r}
# Standard distributions
modlist <- list("Exponential"=mod.exp, "Weibull"=mod.weib, 
                "Generalised Gamma"=mod.gengamma, "Log-normal"=mod.lnorm,
                "Log Logistic"=mod.loglogistic, "Gompertz"=mod.gom)

surv.df <- data.frame()
for (i in seq_along(modlist)) {
  mod.df <- summary(modlist[[i]], tidy=TRUE)
  surv.df <- rbind(surv.df,
                   mod.df %>% rename(surv=est, upper=ucl, lower=lcl) %>%
                     select(time, surv, upper, lower) %>%
                     mutate(Model=names(modlist)[i]))
}

# Add RCS
pred_surv <- predict(mod.rcs, 
                     type="surv", grid=TRUE, full=TRUE, se.fit=TRUE)
surv.df <- rbind(surv.df,
                 pred_surv %>% rename(surv=Estimate) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="RCS")
                   )

# Add fractional polynomial
surv.df <- rbind(surv.df,
                 subset(surv.fp$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order")
                   )

surv.df$Model <- factor(surv.df$Model)

# Plot all results with KM data
kmdat <- survfit(Surv(time, event) ~ 1, data=ipd.ref,type="kaplan-meier",)
kmdat <- data.frame(time=kmdat$time,surv=kmdat$surv, Model="Kaplan-Meier")

cols <- RColorBrewer::brewer.pal(n_distinct(surv.df$Model)+1, "Set1")

ggplot(surv.df, aes(x=time, y=surv, color=Model)) +
  geom_line() +
  geom_step(data=kmdat, aes(time, surv), color="black") +
  xlab("Time (months)") +
  ylab("PFS") +
  scale_color_manual(values=cols) +
  theme_bw()
```

```{r}
knitr::kable(modfit, col.names=c("Distribution", "AIC", "BIC"),
                  digits=1)
```


```{r}
# Generate covariance matrices (fp.mod)
mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "S", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                         rowNames = TRUE, colNames = TRUE)
```


## Save multivariate normal parameters

```{r}
openxlsx::saveWorkbook(wb=wb, file="MVN_ST2_ReferenceCurves.xlsx", overwrite=TRUE)
```

