---
title: "NSCLC - Reference curves for ST1"
author: "Hugo Pedder"
date: "2023-12-01"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  options(knitr.kable.NA = '\\-'),
  fig.height=5, 
  fig.width=12
  )

library(flexsurv)
library(survminer)
library(mfp)
library(rstpm2)
library(ggplot2)
library(tidyverse)
library(BristolTAG)
source("NSCLC_functions.R")

# Choose save location
wb <- openxlsx::createWorkbook(title="ST1_ReferenceCurves")


info.df <- data.frame("Title"=c("Fractional polynomial multivariate normal distribution of MCMC samples - means and covariances for reference model parameters",
                                      "Parameters named by the treatment refer to the relative treatment effect for each fractional polynomial coefficient (1-3)"
                                ))

openxlsx::addWorksheet(wb=wb, sheetName="Info")
openxlsx::writeDataTable(wb=wb, sheet="Info", 
                         x=info.df)
```


## Non-squamous patients

This uses the Docetaxel arm of CHECKMATE-057

```{r}
# Import data
ipd <- read.csv("ST1 PFS IPD extraction.csv")
```


```{r}
ipd.ref <- subset(ipd, study=="CHECKMATE057" & treatment=="Docetaxel" &
                    PDL1=="Pooled")


#### Run models ####
#Exponenetial
mod.exp <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='exponential')
modfit <- data.frame(Model="Exponential", AIC=glance(mod.exp)$AIC, BIC=glance(mod.exp)$BIC)
print("Exponential distribution")
print(mod.exp)

# Weibull
mod.weib <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='WeibullPH')
modfit <- modfit %>%
  add_row(Model="Weibull", AIC=glance(mod.weib)$AIC, BIC=glance(mod.weib)$BIC)
print("Weibull distribution")
print(mod.weib)

# Gamma
mod.gengamma <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gengamma')
modfit <- modfit %>%
  add_row(Model="Generalised Gamma", AIC=glance(mod.gengamma)$AIC, BIC=glance(mod.gengamma)$BIC)
print("Generalised gamma distribution")
print(mod.gengamma)

# Log-normal
mod.lnorm <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='lnorm')
modfit <- modfit %>%
  add_row(Model="Log-Normal", AIC=glance(mod.lnorm)$AIC, BIC=glance(mod.lnorm)$BIC)
print("Log-normal distribution")
print(mod.lnorm)

# Log logistic
mod.loglogistic <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='llogis')
modfit <- modfit %>%
  add_row(Model="Log Logistic", AIC=glance(mod.loglogistic)$AIC, BIC=glance(mod.loglogistic)$BIC)
print("Log-logistic distribution")
print(mod.loglogistic)

# Gompertz
mod.gom <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gompertz')
modfit <- modfit %>%
  add_row(Model="Gompertz", AIC=glance(mod.gom)$AIC, BIC=glance(mod.gom)$BIC)
print("Gompertz distribution")
print(mod.gom)

# RCS (2 knots)
mod.rcs <- stpm2(Surv(time, event)~1, data=ipd.ref, df=2)
modfit <- modfit %>%
  add_row(Model="RCS", AIC=AIC(mod.rcs), BIC=BIC(mod.rcs))
print("Restricted cubic spline (2 knots)")
print(mod.rcs)


# Fractional polynomial (2nd order -0.5, -0.5)
modseq1 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly1_CM057.RDS")
modseq2 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly2_CM057.RDS")
modseq.fp <- append(modseq1, modseq2)
class(modseq.fp) <- "sequence.fpoly"

modfit.fp <- summary(modseq.fp) %>%
  subset(converged==TRUE) %>%
  arrange(DIC)

refstudy <- "CHECKMATE057"

# For selected treatment effects FP model
fp.mod.1 <- modseq.fp[["FP_-0.5_-3"]]

surv.fp.1 <- survcalc(fp.mod.1, 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy)

print("2nd order Fractional Polynomial: same powers as FP treatment model")
params <- fp.mod.1$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.1)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (treatment model powers)", AIC=NA, BIC=NA)


# For FP reference model with lowest DIC 
fp.mod.2 <- modseq.fp[[modfit.fp$model[1]]]

surv.fp.2 <- survcalc(fp.mod.2, 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy)

print("2nd order Fractional Polynomial: lowest DIC")
params <- fp.mod.2$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.2)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (lowest DIC)", AIC=NA, BIC=NA)
```

```{r}
# Standard distributions
modlist <- list("Exponential"=mod.exp, "Weibull"=mod.weib, 
                "Generalised Gamma"=mod.gengamma, "Log-normal"=mod.lnorm,
                "Log Logistic"=mod.loglogistic, "Gompertz"=mod.gom)

surv.df <- data.frame()
for (i in seq_along(modlist)) {
  mod.df <- summary(modlist[[i]], tidy=TRUE)
  surv.df <- rbind(surv.df,
                   mod.df %>% rename(surv=est, upper=ucl, lower=lcl) %>%
                     select(time, surv, upper, lower) %>%
                     mutate(Model=names(modlist)[i]))
}

# Add RCS
pred_surv <- predict(mod.rcs, 
                     type="surv", grid=TRUE, full=TRUE, se.fit=TRUE)
surv.df <- rbind(surv.df,
                 pred_surv %>% rename(surv=Estimate) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="RCS")
                   )

# Add fractional polynomial
surv.df <- rbind(surv.df,
                 subset(surv.fp.1$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (treatment model)"),
                 
                 subset(surv.fp.2$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (lowest DIC)")
                   )


surv.df$Model <- factor(surv.df$Model)

# Plot all results with KM data
kmdat <- survfit(Surv(time, event) ~ 1, data=ipd.ref,type="kaplan-meier",)
kmdat <- data.frame(time=kmdat$time,surv=kmdat$surv, Model="Kaplan-Meier")

cols <- RColorBrewer::brewer.pal(n_distinct(surv.df$Model)+1, "Set1")

ggplot(surv.df, aes(x=time, y=surv, color=Model)) +
  geom_line() +
  geom_step(data=kmdat, aes(time, surv), color="black") +
  xlab("Time (months)") +
  ylab("Survival") +
  scale_color_manual(values=cols) +
  theme_bw()
```

```{r}
knitr::kable(modfit, col.names=c("Distribution", "AIC", "BIC"),
                  digits=1)
```


```{r}
# Generate covariance matrices (fp.mod.1)
fp.mod <- fp.mod.1

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "NS", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                         rowNames = TRUE, colNames = TRUE)

# Generate covariance matrices (fp.mod.2)
fp.mod <- fp.mod.2

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "NS", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
  openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                           rowNames = TRUE, colNames = TRUE)
```

## Squamous patients

This uses the Docetaxel arm of CHECKMATE-017

```{r}
# Import data
ipd <- read.csv("ST1 PFS IPD extraction.csv")
```


```{r}
ipd.ref <- subset(ipd, study=="CHECKMATE017" & treatment=="Docetaxel" &
                    PDL1=="Pooled")


#### Run models ####
#Exponenetial
mod.exp <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='exponential')
modfit <- data.frame(Model="Exponential", AIC=glance(mod.exp)$AIC, BIC=glance(mod.exp)$BIC)
print("Exponential distribution")
print(mod.exp)

# Weibull
mod.weib <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='WeibullPH')
modfit <- modfit %>%
  add_row(Model="Weibull", AIC=glance(mod.weib)$AIC, BIC=glance(mod.weib)$BIC)
print("Weibull distribution")
print(mod.weib)

# Gamma
mod.gengamma <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gengamma')
modfit <- modfit %>%
  add_row(Model="Generalised Gamma", AIC=glance(mod.gengamma)$AIC, BIC=glance(mod.gengamma)$BIC)
print("Generalised gamma distribution")
print(mod.gengamma)

# Log-normal
mod.lnorm <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='lnorm')
modfit <- modfit %>%
  add_row(Model="Log-Normal", AIC=glance(mod.lnorm)$AIC, BIC=glance(mod.lnorm)$BIC)
print("Log-normal distribution")
print(mod.lnorm)

# Log logistic
mod.loglogistic <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='llogis')
modfit <- modfit %>%
  add_row(Model="Log Logistic", AIC=glance(mod.loglogistic)$AIC, BIC=glance(mod.loglogistic)$BIC)
print("Log-logistic distribution")
print(mod.loglogistic)

# Gompertz
mod.gom <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gompertz')
modfit <- modfit %>%
  add_row(Model="Gompertz", AIC=glance(mod.gom)$AIC, BIC=glance(mod.gom)$BIC)
print("Gompertz distribution")
print(mod.gom)

# RCS (2 knots)
mod.rcs <- stpm2(Surv(time, event)~1, data=ipd.ref, df=2)
modfit <- modfit %>%
  add_row(Model="RCS", AIC=AIC(mod.rcs), BIC=BIC(mod.rcs))
print("Restricted cubic spline (2 knots)")
print(mod.rcs)

# Fractional polynomial (2nd order -0.5, -0.5)
modseq1 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly1_CM017.RDS")
modseq2 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly2_CM017.RDS")
modseq.fp <- append(modseq1, modseq2)
class(modseq.fp) <- "sequence.fpoly"

modfit.fp <- summary(modseq.fp) %>%
  subset(converged==TRUE) %>%
  arrange(DIC)

refstudy <- "CHECKMATE017"

# For selected FP model
fp.mod.1 <- modseq.fp[["FP_-3_-0.5"]]

surv.fp.1 <- survcalc(fp.mod.1, 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy)

print("2nd order Fractional Polynomial: Same powers as treatment effect model")
params <- fp.mod.1$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.1)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (treatment effects model)", AIC=NA, BIC=NA)


# For FP reference model with lowest DIC 
fp.mod.2 <- modseq.fp[[modfit.fp$model[1]]]

surv.fp.2 <- survcalc(fp.mod.2, 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy)

print("2nd order Fractional Polynomial: lowest DIC")
params <- fp.mod.2$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.2)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (lowest DIC)", AIC=NA, BIC=NA)
```

```{r}
# Standard distributions
modlist <- list("Exponential"=mod.exp, "Weibull"=mod.weib, 
                "Generalised Gamma"=mod.gengamma, "Log-normal"=mod.lnorm,
                "Log Logistic"=mod.loglogistic, "Gompertz"=mod.gom)

surv.df <- data.frame()
for (i in seq_along(modlist)) {
  mod.df <- summary(modlist[[i]], tidy=TRUE)
  surv.df <- rbind(surv.df,
                   mod.df %>% rename(surv=est, upper=ucl, lower=lcl) %>%
                     select(time, surv, upper, lower) %>%
                     mutate(Model=names(modlist)[i]))
}

# Add RCS
pred_surv <- predict(mod.rcs, 
                     type="surv", grid=TRUE, full=TRUE, se.fit=TRUE)
surv.df <- rbind(surv.df,
                 pred_surv %>% rename(surv=Estimate) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="RCS")
                   )

# Add fractional polynomial
surv.df <- rbind(surv.df,
                 subset(surv.fp.1$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (treatment model)"),
                 
                 subset(surv.fp.2$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (lowest DIC)")
                   )

surv.df$Model <- factor(surv.df$Model)

# Plot all results with KM data
kmdat <- survfit(Surv(time, event) ~ 1, data=ipd.ref,type="kaplan-meier",)
kmdat <- data.frame(time=kmdat$time,surv=kmdat$surv, Model="Kaplan-Meier")

cols <- RColorBrewer::brewer.pal(n_distinct(surv.df$Model)+1, "Set1")

ggplot(surv.df, aes(x=time, y=surv, color=Model)) +
  geom_line() +
  geom_step(data=kmdat, aes(time, surv), color="black") +
  xlab("Time (months)") +
  ylab("Survival") +
  scale_color_manual(values=cols) +
  theme_bw()
```

```{r}
knitr::kable(modfit, col.names=c("Distribution", "AIC", "BIC"),
                  digits=1)
```

```{r}
# Generate covariance matrices (fp.mod.1)
fp.mod <- fp.mod.1

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "S", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                         rowNames = TRUE, colNames = TRUE)

# Generate covariance matrices (fp.mod.2)
fp.mod <- fp.mod.2

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "S", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
  openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                           rowNames = TRUE, colNames = TRUE)
```


## RET fusion + patients

This uses the Selpercatinib arm of LIBRETTO-001

```{r}
# Import data
ipd <- read.csv("ST1 PFS IPD extraction.csv")
```


```{r}
ipd.ref <- subset(ipd, study=="LIBRETTO-001" & treatment=="Selpercatinib")


#### Run models ####
#Exponenetial
mod.exp <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='exponential')
modfit <- data.frame(Model="Exponential", AIC=glance(mod.exp)$AIC, BIC=glance(mod.exp)$BIC)
print("Exponential distribution")
print(mod.exp)

# Weibull
mod.weib <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='WeibullPH')
modfit <- modfit %>%
  add_row(Model="Weibull", AIC=glance(mod.weib)$AIC, BIC=glance(mod.weib)$BIC)
print("Weibull distribution")
print(mod.weib)

# Gamma
mod.gengamma <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gengamma')
modfit <- modfit %>%
  add_row(Model="Generalised Gamma", AIC=glance(mod.gengamma)$AIC, BIC=glance(mod.gengamma)$BIC)
print("Generalised gamma distribution")
print(mod.gengamma)

# Log-normal
mod.lnorm <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='lnorm')
modfit <- modfit %>%
  add_row(Model="Log-Normal", AIC=glance(mod.lnorm)$AIC, BIC=glance(mod.lnorm)$BIC)
print("Log-normal distribution")
print(mod.lnorm)

# Log logistic
mod.loglogistic <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='llogis')
modfit <- modfit %>%
  add_row(Model="Log Logistic", AIC=glance(mod.loglogistic)$AIC, BIC=glance(mod.loglogistic)$BIC)
print("Log-logistic distribution")
print(mod.loglogistic)

# Gompertz
mod.gom <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gompertz')
modfit <- modfit %>%
  add_row(Model="Gompertz", AIC=glance(mod.gom)$AIC, BIC=glance(mod.gom)$BIC)
print("Gompertz distribution")
print(mod.gom)

# RCS (2 knots)
mod.rcs <- stpm2(Surv(time, event)~1, data=ipd.ref, df=2)
modfit <- modfit %>%
  add_row(Model="RCS", AIC=AIC(mod.rcs), BIC=BIC(mod.rcs))
print("Restricted cubic spline (2 knots)")
print(mod.rcs)

# Fractional polynomial (2nd order -0.5, -0.5)
modseq1 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly1_LIBRETTO-001.RDS")
modseq2 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly2_LIBRETTO-001.RDS")
modseq.fp <- append(modseq1, modseq2)
class(modseq.fp) <- "sequence.fpoly"

modfit.fp <- summary(modseq.fp) %>%
  subset(converged==TRUE & !is.na(P2)) %>%
  arrange(DIC)

# For FP -1 0
# surv.fp <- survcalc(modseq.fp[["FP_-3_-0.5"]], 
#                     times=seq(1, max(ipd$time[ipd$study=="LIBRETTO-001"]), length.out = 100),
#                     refstudy="LIBRETTO-001")

refstudy <- "LIBRETTO-001"


# Slight fudge to allow survcalc to run with reference model
fp.mod.1 <- modseq.fp[["FP_-3_-0.5"]]

surv.fp.1 <- survcalc(readRDS(file="JAGS_Results/ST1_PFS_fpoly2_CM017.RDS")[["FP_-3_-0.5"]], 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy,
                    refmod=fp.mod.1)

print("2nd order Fractional Polynomial: Same powers as treatment effect model")
params <- fp.mod.1$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.1)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)


modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (treatment effects model)", AIC=NA, BIC=NA)



# For FP reference model with lowest DIC 
fp.mod.2 <- modseq.fp[[modfit.fp$model[1]]]

surv.fp.2 <- survcalc(readRDS(file="JAGS_Results/ST1_PFS_fpoly2_CM017.RDS")[[modfit.fp$model[1]]],
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy,
                    refmod=fp.mod.2)

print("2nd order Fractional Polynomial: lowest DIC")
params <- fp.mod.2$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.2)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (lowest DIC)", AIC=NA, BIC=NA)
```

```{r}
# Standard distributions
modlist <- list("Exponential"=mod.exp, "Weibull"=mod.weib, 
                "Generalised Gamma"=mod.gengamma, "Log-normal"=mod.lnorm,
                "Log Logistic"=mod.loglogistic, "Gompertz"=mod.gom)

surv.df <- data.frame()
for (i in seq_along(modlist)) {
  mod.df <- summary(modlist[[i]], tidy=TRUE)
  surv.df <- rbind(surv.df,
                   mod.df %>% rename(surv=est, upper=ucl, lower=lcl) %>%
                     select(time, surv, upper, lower) %>%
                     mutate(Model=names(modlist)[i]))
}

# Add RCS
pred_surv <- predict(mod.rcs, 
                     type="surv", grid=TRUE, full=TRUE, se.fit=TRUE)
surv.df <- rbind(surv.df,
                 pred_surv %>% rename(surv=Estimate) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="RCS")
                   )

# Add fractional polynomial
surv.df <- rbind(surv.df,
                 subset(surv.fp.1$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (treatment model)"),
                 
                 subset(surv.fp.2$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (lowest DIC)")
                   )

surv.df$Model <- factor(surv.df$Model)

# Plot all results with KM data
kmdat <- survfit(Surv(time, event) ~ 1, data=ipd.ref,type="kaplan-meier",)
kmdat <- data.frame(time=kmdat$time,surv=kmdat$surv, Model="Kaplan-Meier")

cols <- RColorBrewer::brewer.pal(n_distinct(surv.df$Model)+1, "Set1")

ggplot(surv.df, aes(x=time, y=surv, color=Model)) +
  geom_line() +
  geom_step(data=kmdat, aes(time, surv), color="black") +
  xlab("Time (months)") +
  ylab("Survival") +
  scale_color_manual(values=cols) +
  theme_bw()
```

```{r}
knitr::kable(modfit, col.names=c("Distribution", "AIC", "BIC"),
                  digits=1)
```

```{r}
# Generate covariance matrices (fp.mod.1)
fp.mod <- fp.mod.1

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "RET+", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                         rowNames = TRUE, colNames = TRUE)

# Generate covariance matrices (fp.mod.2)
fp.mod <- fp.mod.2

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "RET+", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
  openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                           rowNames = TRUE, colNames = TRUE)
```


## KRAS population

This uses the Docetaxel arm of CODEBREAK200

```{r}
# Import data
ipd <- read.csv("ST1 PFS IPD extraction.csv")
```

```{r}
ipd.ref <- subset(ipd, study=="CODEBREAK200" & treatment=="Docetaxel")


#### Run models ####
#Exponenetial
mod.exp <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='exponential')
modfit <- data.frame(Model="Exponential", AIC=glance(mod.exp)$AIC, BIC=glance(mod.exp)$BIC)
print("Exponential distribution")
print(mod.exp)

# Weibull
mod.weib <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='WeibullPH')
modfit <- modfit %>%
  add_row(Model="Weibull", AIC=glance(mod.weib)$AIC, BIC=glance(mod.weib)$BIC)
print("Weibull distribution")
print(mod.weib)

# Gamma
mod.gengamma <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gengamma')
modfit <- modfit %>%
  add_row(Model="Generalised Gamma", AIC=glance(mod.gengamma)$AIC, BIC=glance(mod.gengamma)$BIC)
print("Generalised gamma distribution")
print(mod.gengamma)

# Log-normal
mod.lnorm <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='lnorm')
modfit <- modfit %>%
  add_row(Model="Log-Normal", AIC=glance(mod.lnorm)$AIC, BIC=glance(mod.lnorm)$BIC)
print("Log-normal distribution")
print(mod.lnorm)

# Log logistic
mod.loglogistic <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='llogis')
modfit <- modfit %>%
  add_row(Model="Log Logistic", AIC=glance(mod.loglogistic)$AIC, BIC=glance(mod.loglogistic)$BIC)
print("Log-logistic distribution")
print(mod.loglogistic)

# Gompertz
mod.gom <- flexsurvreg(Surv(time, event)~1, data=ipd.ref, dist='gompertz')
modfit <- modfit %>%
  add_row(Model="Gompertz", AIC=glance(mod.gom)$AIC, BIC=glance(mod.gom)$BIC)
print("Gompertz distribution")
print(mod.gom)

# RCS (2 knots)
mod.rcs <- stpm2(Surv(time, event)~1, data=ipd.ref, df=2)
modfit <- modfit %>%
  add_row(Model="RCS", AIC=AIC(mod.rcs), BIC=BIC(mod.rcs))
print("Restricted cubic spline (2 knots)")
print(mod.rcs)


# Fractional polynomial (2nd order)
modseq1 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly1_CODEBREAK200.RDS")
modseq2 <- readRDS(file="JAGS_Results/ST1_PFS_fpoly2_CODEBREAK200.RDS")
modseq.fp <- append(modseq1, modseq2)
class(modseq.fp) <- "sequence.fpoly"

summary(modseq.fp) %>%
  subset(converged==TRUE) %>%
  arrange(DIC)

refstudy <- "CODEBREAK200"


# For selected treatment effects FP model
fp.mod.1 <- modseq.fp[["FP_-3_-0.5"]]

surv.fp.1 <- survcalc(fp.mod.1, 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy)

print("2nd order Fractional Polynomial: same powers as FP treatment model")
params <- fp.mod.1$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.1)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (treatment model powers)", AIC=NA, BIC=NA)


# For FP reference model with lowest DIC 
fp.mod.2 <- modseq.fp[[modfit.fp$model[1]]]

surv.fp.2 <- survcalc(fp.mod.2, 
                    times=seq(1, max(ipd.ref$time), length.out = 100),
                    refstudy=refstudy)

print("2nd order Fractional Polynomial: lowest DIC")
params <- fp.mod.2$BUGSoutput$summary[
  paste0("mu[", which(attributes(fp.mod.2)$studynames %in% refstudy), ",", 1:3, "]"),
  ]
print(params)

modfit <- modfit %>%
  add_row(Model="2nd order fractional polynomial (lowest DIC)", AIC=NA, BIC=NA)
```

```{r}
# Standard distributions
modlist <- list("Exponential"=mod.exp, "Weibull"=mod.weib, 
                "Generalised Gamma"=mod.gengamma, "Log-normal"=mod.lnorm,
                "Log Logistic"=mod.loglogistic, "Gompertz"=mod.gom)

surv.df <- data.frame()
for (i in seq_along(modlist)) {
  mod.df <- summary(modlist[[i]], tidy=TRUE)
  surv.df <- rbind(surv.df,
                   mod.df %>% rename(surv=est, upper=ucl, lower=lcl) %>%
                     select(time, surv, upper, lower) %>%
                     mutate(Model=names(modlist)[i]))
}

# Add RCS
pred_surv <- predict(mod.rcs, 
                     type="surv", grid=TRUE, full=TRUE, se.fit=TRUE)
surv.df <- rbind(surv.df,
                 pred_surv %>% rename(surv=Estimate) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="RCS")
                   )

# Add fractional polynomial
surv.df <- rbind(surv.df,
                 subset(surv.fp.1$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (treatment model)"),
                 
                 subset(surv.fp.2$S, treatment=="Docetaxel") %>% 
                   rename(surv=`50%`, lower=`2.5%`, upper=`97.5%`) %>%
                   select(time, surv, upper, lower) %>%
                   mutate(Model="Frac Poly 2nd order (lowest DIC)")
                   )

surv.df$Model <- factor(surv.df$Model)

# Plot all results with KM data
kmdat <- survfit(Surv(time, event) ~ 1, data=ipd.ref,type="kaplan-meier",)
kmdat <- data.frame(time=kmdat$time,surv=kmdat$surv, Model="Kaplan-Meier")

cols <- RColorBrewer::brewer.pal(n_distinct(surv.df$Model)+1, "Set1")

ggplot(surv.df, aes(x=time, y=surv, color=Model)) +
  geom_line() +
  geom_step(data=kmdat, aes(time, surv), color="black") +
  xlab("Time (months)") +
  ylab("Survival") +
  scale_color_manual(values=cols) +
  theme_bw()
```

```{r}
knitr::kable(modfit, col.names=c("Distribution", "AIC", "BIC"),
                  digits=1)
```

```{r}
# Generate covariance matrices (fp.mod.1)
fp.mod <- fp.mod.1

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "KRAS", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                         rowNames = TRUE, colNames = TRUE)

# Generate covariance matrices (fp.mod.2)
fp.mod <- fp.mod.2

mvn <- output_coda_ref(fp.mod.1 = fp.mod, refstudy=refstudy)

sheetnam <- paste("FP", fp.mod$model$data()$P1, fp.mod$model$data()$P2, "KRAS", sep="_")
openxlsx::addWorksheet(wb=wb, sheetName=sheetnam)

openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$mean), rowNames = TRUE)
  openxlsx::writeDataTable(wb=wb, sheet=sheetnam, data.frame(mvn$covar), startCol=4,
                           rowNames = TRUE, colNames = TRUE)
```


## Save covariance matrices

```{r}
openxlsx::saveWorkbook(wb=wb, file="MVN_ST1_ReferenceCurves.xlsx", overwrite=TRUE)
```
